ACCEPT_KEYWORDS="~amd64"

# COMPILER FLAGS
COMMON_FLAGS="-march=native -O2 -pipe -flto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${LDFLAGS} -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed"
RUSTFLAGS="-C target-cpu=native -C opt-level=3"
MAKEOPTS="-j8"

CHOST="x86_64-pc-linux-musl"
ACCEPT_LICENSE="*"
C_MESSAGES=C.utf8
L10N="en en-US"
GENTOO_MIRRORS="ftp://ftp.free.fr/mirrors/ftp.gentoo.org/ \
    https://mirror.bytemark.co.uk/gentoo/ \
    rsync://ftp.agdsn.de/gentoo \
    https://mirrors.tnonline.net/gentoo/gentoo-distfiles/ \
    https://ftp.agdsn.de/gentoo"
EMERGE_DEFAULT_OPTS="--alphabetical --autounmask-write=n --complete-graph=y --keep-going --verbose --verbose-conflicts --with-bdeps=y --backtrack=100 --buildpkg-exclude virtual/* --ignore-built-slot-operator-deps y"

GRUB_PLATFORMS="efi-64"
VIDEO_CARDS="amdgpu radeon radeonsi"
QEMU_SOFTMMU_TARGETS="arm x86_64 i386"
QEMU_USER_TARGETS="x86_64"

USE="-nls -acl -systemd -kde -gnome \
-X -cuda -wifi -ios -ipod -xemacs   \
-ieee1394 -emacs hip openrc grub    \
installkernel dracut llvm clang     \
compiler-rt llvm-libunwind lto pgo  \
wayland Xwayland alsa pipewire	    \
openh264 png jpg svg webp zstd usb  \
udev elogind dbus vulkan opengl     \ 
mesa pulseaudio sound-server"
